// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfUNujDfbmu_5GxHkFwlrwzdqFzk1knqU',
    appId: '1:835832710538:web:9d3e350677e6cea729f473',
    messagingSenderId: '835832710538',
    projectId: 'pasarkitadb',
    authDomain: 'pasarkitadb.firebaseapp.com',
    storageBucket: 'pasarkitadb.firebasestorage.app',
    measurementId: 'G-TD6YFNGK2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnutyeULZfMw7_FfyEw3FuIifdg-qbAv8',
    appId: '1:835832710538:android:7bd174fcb048134f29f473',
    messagingSenderId: '835832710538',
    projectId: 'pasarkitadb',
    storageBucket: 'pasarkitadb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfUNujDfbmu_5GxHkFwlrwzdqFzk1knqU',
    appId: '1:835832710538:web:25e85c296c7fb03829f473',
    messagingSenderId: '835832710538',
    projectId: 'pasarkitadb',
    authDomain: 'pasarkitadb.firebaseapp.com',
    storageBucket: 'pasarkitadb.firebasestorage.app',
    measurementId: 'G-G12P2YG83J',
  );
}
